import { ThemeConfig, LanguageConfig } from '../types/themes';

export const THEMES: ThemeConfig[] = [
  // ================= 8 LIGHT THEMES =================
  {
    id: 'classic-ivory',
    name: 'Classic Ivory',
    category: 'light',
    description: 'Warm parchment paper with rich slate navy headers and deep archival ink typography.',
    bgHex: '#FAF7F0',
    textHex: '#1E293B',
    headerAccentHex: '#1E3A8A',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#E2D9C8',
    tableHeaderBgHex: '#1E3A8A',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#F6F2E8',
    tableBorderHex: '#DFD5C2',
    codeBgHex: '#F1ECE1',
    codeTextHex: '#0F172A',
    codeBorderHex: '#DACFBC',
    katexColorHex: '#1E3A8A',
    badgeBgHex: '#E8E1D3',
    badgeTextHex: '#1E293B',
    accentHex: '#2563EB',
    accentHoverHex: '#1D4ED8',
  },
  {
    id: 'oxford-academic',
    name: 'Oxford Academic',
    category: 'light',
    description: 'Crisp alabaster backdrop with collegiate Oxford deep navy and cobalt accents.',
    bgHex: '#F8FAFC',
    textHex: '#0F172A',
    headerAccentHex: '#002147',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#CBD5E1',
    tableHeaderBgHex: '#002147',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#F1F5F9',
    tableBorderHex: '#CBD5E1',
    codeBgHex: '#E2E8F0',
    codeTextHex: '#002147',
    codeBorderHex: '#94A3B8',
    katexColorHex: '#002147',
    badgeBgHex: '#E0E7FF',
    badgeTextHex: '#1E1B4B',
    accentHex: '#1D4ED8',
    accentHoverHex: '#1E40AF',
  },
  {
    id: 'mit-slate',
    name: 'MIT Slate',
    category: 'light',
    description: 'Technical ice-white canvas, modern engineering slate gray, and precise cyan accents.',
    bgHex: '#F3F4F6',
    textHex: '#111827',
    headerAccentHex: '#1F2937',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#D1D5DB',
    tableHeaderBgHex: '#374151',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#F9FAFB',
    tableBorderHex: '#E5E7EB',
    codeBgHex: '#E5E7EB',
    codeTextHex: '#111827',
    codeBorderHex: '#D1D5DB',
    katexColorHex: '#0369A1',
    badgeBgHex: '#E0F2FE',
    badgeTextHex: '#0369A1',
    accentHex: '#0284C7',
    accentHoverHex: '#0369A1',
  },
  {
    id: 'harvard-crimson',
    name: 'Harvard Crimson',
    category: 'light',
    description: 'Linen white base with prestigious deep collegiate crimson #800000 and warm gold borders.',
    bgHex: '#FFFDFD',
    textHex: '#262626',
    headerAccentHex: '#800000',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#E8D5D5',
    tableHeaderBgHex: '#800000',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#FFF5F5',
    tableBorderHex: '#E8D5D5',
    codeBgHex: '#F9EEEE',
    codeTextHex: '#800000',
    codeBorderHex: '#DFBDBD',
    katexColorHex: '#800000',
    badgeBgHex: '#FFE4E6',
    badgeTextHex: '#9F1239',
    accentHex: '#991B1B',
    accentHoverHex: '#7F1D1D',
  },
  {
    id: 'cambridge-emerald',
    name: 'Cambridge Emerald',
    category: 'light',
    description: 'Fresh botanical mist white with rich British racing green #004D40 and jade highlights.',
    bgHex: '#F6FBF8',
    textHex: '#064E3B',
    headerAccentHex: '#004D40',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#A7F3D0',
    tableHeaderBgHex: '#004D40',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#ECFDF5',
    tableBorderHex: '#A7F3D0',
    codeBgHex: '#E6F4EA',
    codeTextHex: '#004D40',
    codeBorderHex: '#A7F3D0',
    katexColorHex: '#047857',
    badgeBgHex: '#D1FAE5',
    badgeTextHex: '#065F46',
    accentHex: '#059669',
    accentHoverHex: '#047857',
  },
  {
    id: 'caltech-solar',
    name: 'Caltech Solar',
    category: 'light',
    description: 'Warm titanium canvas with intense solar amber, burnt bronze, and high-energy physics vibe.',
    bgHex: '#FFFBF5',
    textHex: '#27272A',
    headerAccentHex: '#B45309',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#FDE68A',
    tableHeaderBgHex: '#B45309',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#FEF3C7',
    tableBorderHex: '#FCD34D',
    codeBgHex: '#FEF3C7',
    codeTextHex: '#92400E',
    codeBorderHex: '#FDE68A',
    katexColorHex: '#B45309',
    badgeBgHex: '#FEF3C7',
    badgeTextHex: '#92400E',
    accentHex: '#D97706',
    accentHoverHex: '#B45309',
  },
  {
    id: 'royal-violet',
    name: 'Royal Violet',
    category: 'light',
    description: 'Lavender-tinted dew white with majestic imperial violet headers and crisp dark type.',
    bgHex: '#FAF8FF',
    textHex: '#1E1B4B',
    headerAccentHex: '#4C1D95',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#DDD6FE',
    tableHeaderBgHex: '#4C1D95',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#F5F3FF',
    tableBorderHex: '#DDD6FE',
    codeBgHex: '#EDE9FE',
    codeTextHex: '#4C1D95',
    codeBorderHex: '#DDD6FE',
    katexColorHex: '#5B21B6',
    badgeBgHex: '#EDE9FE',
    badgeTextHex: '#5B21B6',
    accentHex: '#7C3AED',
    accentHoverHex: '#6D28D9',
  },
  {
    id: 'swiss-minimalist',
    name: 'Swiss Minimalist',
    category: 'light',
    description: 'Pure 100% white with razor-sharp black typography, structured hairline grids, and Helvetica red touch.',
    bgHex: '#FFFFFF',
    textHex: '#000000',
    headerAccentHex: '#000000',
    cardBgHex: '#FFFFFF',
    cardBorderHex: '#000000',
    tableHeaderBgHex: '#000000',
    tableHeaderTextHex: '#FFFFFF',
    tableRowEvenHex: '#FFFFFF',
    tableRowOddHex: '#F3F4F6',
    tableBorderHex: '#000000',
    codeBgHex: '#F3F4F6',
    codeTextHex: '#000000',
    codeBorderHex: '#000000',
    katexColorHex: '#000000',
    badgeBgHex: '#000000',
    badgeTextHex: '#FFFFFF',
    accentHex: '#DC2626',
    accentHoverHex: '#B91C1C',
  },

  // ================= 7 DARK/OLED THEMES =================
  {
    id: 'obsidian-oled',
    name: 'Pure OLED Obsidian',
    category: 'dark',
    description: 'True pitch black #000000 with ultra-high contrast crisp white type and electric cyan formula glow.',
    bgHex: '#000000',
    textHex: '#F8FAFC',
    headerAccentHex: '#38BDF8',
    cardBgHex: '#080808',
    cardBorderHex: '#262626',
    tableHeaderBgHex: '#0F172A',
    tableHeaderTextHex: '#38BDF8',
    tableRowEvenHex: '#050505',
    tableRowOddHex: '#0C0C0C',
    tableBorderHex: '#27272A',
    codeBgHex: '#0A0A0A',
    codeTextHex: '#38BDF8',
    codeBorderHex: '#262626',
    katexColorHex: '#38BDF8',
    badgeBgHex: '#082F49',
    badgeTextHex: '#7DD3FC',
    accentHex: '#0EA5E9',
    accentHoverHex: '#38BDF8',
  },
  {
    id: 'deep-midnight',
    name: 'Deep Midnight',
    category: 'dark',
    description: 'Atmospheric midnight sapphire #090D16 with luminous stellar blue and cobalt card accents.',
    bgHex: '#090D16',
    textHex: '#E2E8F0',
    headerAccentHex: '#60A5FA',
    cardBgHex: '#0E1524',
    cardBorderHex: '#1E293B',
    tableHeaderBgHex: '#131D31',
    tableHeaderTextHex: '#93C5FD',
    tableRowEvenHex: '#0B111D',
    tableRowOddHex: '#101827',
    tableBorderHex: '#1E293B',
    codeBgHex: '#111A2C',
    codeTextHex: '#93C5FD',
    codeBorderHex: '#1E293B',
    katexColorHex: '#60A5FA',
    badgeBgHex: '#172554',
    badgeTextHex: '#BFDBFE',
    accentHex: '#3B82F6',
    accentHoverHex: '#60A5FA',
  },
  {
    id: 'matrix-cyber',
    name: 'Matrix Cyber',
    category: 'dark',
    description: 'Carbon black with phosphorus emerald luminescence #10B981 and hacker-grade terminal aesthetic.',
    bgHex: '#060B08',
    textHex: '#D1FAE5',
    headerAccentHex: '#10B981',
    cardBgHex: '#0A130E',
    cardBorderHex: '#065F46',
    tableHeaderBgHex: '#064E3B',
    tableHeaderTextHex: '#A7F3D0',
    tableRowEvenHex: '#08110B',
    tableRowOddHex: '#0C1A11',
    tableBorderHex: '#065F46',
    codeBgHex: '#064E3B',
    codeTextHex: '#34D399',
    codeBorderHex: '#059669',
    katexColorHex: '#34D399',
    badgeBgHex: '#022C22',
    badgeTextHex: '#6EE7B7',
    accentHex: '#10B981',
    accentHoverHex: '#34D399',
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'dark',
    description: 'Vanta deep violet #0B0714 with vibrant ultraviolet #C084FC and laser fuchsia accents.',
    bgHex: '#0B0714',
    textHex: '#F3E8FF',
    headerAccentHex: '#C084FC',
    cardBgHex: '#140E24',
    cardBorderHex: '#3B1D66',
    tableHeaderBgHex: '#251240',
    tableHeaderTextHex: '#E9D5FF',
    tableRowEvenHex: '#0E091A',
    tableRowOddHex: '#17102A',
    tableBorderHex: '#3B1D66',
    codeBgHex: '#1C1333',
    codeTextHex: '#E879F9',
    codeBorderHex: '#581C87',
    katexColorHex: '#E879F9',
    badgeBgHex: '#3B0764',
    badgeTextHex: '#F0ABFC',
    accentHex: '#A855F7',
    accentHoverHex: '#C084FC',
  },
  {
    id: 'nordic-frost',
    name: 'Nordic Frost',
    category: 'dark',
    description: 'Sub-zero arctic graphite #111827 with glacier ice blue #7DD3FC and crystalline highlights.',
    bgHex: '#0F172A',
    textHex: '#F1F5F9',
    headerAccentHex: '#38BDF8',
    cardBgHex: '#1E293B',
    cardBorderHex: '#334155',
    tableHeaderBgHex: '#334155',
    tableHeaderTextHex: '#BAE6FD',
    tableRowEvenHex: '#141E33',
    tableRowOddHex: '#1E293B',
    tableBorderHex: '#334155',
    codeBgHex: '#0F172A',
    codeTextHex: '#7DD3FC',
    codeBorderHex: '#334155',
    katexColorHex: '#38BDF8',
    badgeBgHex: '#0C4A6E',
    badgeTextHex: '#E0F2FE',
    accentHex: '#0EA5E9',
    accentHoverHex: '#38BDF8',
  },
  {
    id: 'espresso-roast',
    name: 'Espresso Roast',
    category: 'dark',
    description: 'Dark roasted artisanal cocoa #140E0A with warm caramel gold #F59E0B and vintage brass accents.',
    bgHex: '#140E0A',
    textHex: '#FEF3C7',
    headerAccentHex: '#FBBF24',
    cardBgHex: '#1F1712',
    cardBorderHex: '#452A1C',
    tableHeaderBgHex: '#362114',
    tableHeaderTextHex: '#FDE68A',
    tableRowEvenHex: '#17110C',
    tableRowOddHex: '#221913',
    tableBorderHex: '#452A1C',
    codeBgHex: '#261B14',
    codeTextHex: '#FCD34D',
    codeBorderHex: '#583623',
    katexColorHex: '#F59E0B',
    badgeBgHex: '#451A03',
    badgeTextHex: '#FDE68A',
    accentHex: '#D97706',
    accentHoverHex: '#F59E0B',
  },
  {
    id: 'dark-crimson',
    name: 'Dark Crimson',
    category: 'dark',
    description: 'Velvet charcoal abyss #12090D with radiant ruby rose #FB7185 and bold collegiate vigor.',
    bgHex: '#12090D',
    textHex: '#FFE4E6',
    headerAccentHex: '#FB7185',
    cardBgHex: '#1C0F16',
    cardBorderHex: '#4C1D2B',
    tableHeaderBgHex: '#381220',
    tableHeaderTextHex: '#FECDD3',
    tableRowEvenHex: '#150B10',
    tableRowOddHex: '#201119',
    tableBorderHex: '#4C1D2B',
    codeBgHex: '#26121C',
    codeTextHex: '#FDA4AF',
    codeBorderHex: '#5C1D2F',
    katexColorHex: '#FB7185',
    badgeBgHex: '#4C0519',
    badgeTextHex: '#FFE4E6',
    accentHex: '#E11D48',
    accentHoverHex: '#FB7185',
  },
];

export const LANGUAGES: LanguageConfig[] = [
  {
    code: 'ar-EG',
    name: 'Egyptian Arabic (Default)',
    nativeName: 'عامية مصرية (افتراضي)',
    dir: 'rtl',
    flag: '🇪🇬',
    tagline: 'شرح أكاديمي دقيق ومبسط بالعامية المصرية الأصيلة مع الحفاظ الكامل على المعادلات والمصطلحات الدولية',
  },
  {
    code: 'ar-SA',
    name: 'Modern Standard Arabic',
    nativeName: 'العربية الفصحى',
    dir: 'rtl',
    flag: '🇸🇦',
    tagline: 'صياغة أكاديمية فصحى معيارية فائقة الدقة والبيان للمراجع والرسائل العلمية',
  },
  {
    code: 'en-US',
    name: 'English (Academic)',
    nativeName: 'English (US/UK)',
    dir: 'ltr',
    flag: '🇺🇸',
    tagline: 'Rigorous international peer-reviewed academic style with precise definitions and derivations',
  },
  {
    code: 'fr-FR',
    name: 'French',
    nativeName: 'Français',
    dir: 'ltr',
    flag: '🇫🇷',
    tagline: 'Style académique rigoureux pour les grandes écoles et universités de médecine et ingénierie',
  },
  {
    code: 'de-DE',
    name: 'German',
    nativeName: 'Deutsch',
    dir: 'ltr',
    flag: '🇩🇪',
    tagline: 'Präzise ingenieurwissenschaftliche und mathematische Terminologie nach DIN-Norm',
  },
  {
    code: 'es-ES',
    name: 'Spanish',
    nativeName: 'Español',
    dir: 'ltr',
    flag: '🇪🇸',
    tagline: 'Explicación técnica y científica universitaria clara y estructurada sin duplicidad',
  },
];
